### ISSUE TITLE
Only display decimals if needed

### ISSUE THREAD

**Issue by dalholm** [archtechx/money#11]
It would be awesome if there was a setting to show decimals only if needed.

**Comment by stancl** [comment]
I'm thinking we could perhaps move the formatting logic to the currency classes, optionally.

**Comment by dalholm** [comment]
That would be awesome! :)

**Comment by dalholm** [comment]
One more reason why adding custom formatting: Number plus currency (ISO 4217) E.g 150.00 USD  [Googles sale_price](https://support.google.com/merchants/answer/6324471?hl=en)

**Comment by stancl** [comment]
I think you could pass a suffix to the `$money->formatted()` args

**Comment by 4ice** [comment]
Hi! I have made a PR for this. Could you please review it? https://github.com/archtechx/money/pull/18
