### ISSUE TITLE
Money class is final

### ISSUE THREAD

**Issue by Naoray** [archtechx/money#12]
I wanted to add a custom object cast for the `Money`, but unfortunately the class is marked as final and therefore can't be extended. I got around this by creating another class which uses the packages money class under the hood, but it would be much more convenient if I could extend your package's money class.

Any chance you drop the `final` keyword?

**Comment by stancl** [comment]
The keyword is there intentionally, as the class shouldn't ever be extended. I believe that you can use model casts even without changing the `Money` class itself. Or do you have some other casts in mind?

**Comment by Naoray** [comment]
I wanted to utilize the Money class as a DTO using Jess Archers `CastableDataTransferObject` [package](https://github.com/jessarcher/laravel-castable-data-transfer-object).

sure it's possible to have another class, but it would be more convenient if I could use one class as DTO which also have your Money functionality under the hood

**Comment by stancl** [comment]
> sure it's possible to have another class

I'm not talking about that, I'm saying that e.g. model casts let you define how to cast class A using class B.
