### ISSUE TITLE
Change currency

### ISSUE THREAD

**Issue by dalholm** [archtechx/money#7]
I have used several different currency packages. So maybe I'm using this package incorrectly.

I have added two currencies, SEK and EUR with SEK as default.
EUR has a rate of `0.097027` in relation to SEK.

If I use the helper `money` and then run` currencies()->setCurrent ('EUR'); ` only suffixes and prefixes are affected. Prices are still in SEK value. So they have not been converted.

Do I have to use `convertTo()` too or how is the idea to work? I expected all prices to be converted to EURO.

**Comment by stancl** [comment]
Can you show the currency classes and some sample code that reproduces this?

**Comment by dalholm** [comment]
@stancl  Here is a sample of what i am trying to do. 

```php
currencies()->reset();
                    
currencies()->add(
  new \ArchTech\Money\Currency(
  	'SEK',
	'Swedish Kronor',
	1.0,
	'',
	' kr',
	2,
	2,
	null,
	'.',
	' '
  )
);
currencies()->add(
  new \ArchTech\Money\Currency(
  	'EUR',
	'Euro',
	0.097027,
	'€',
	'',
	2,
	2,
	null,
	'.',
	' '
  )
);
currencies()->setDefault('SEK');

$money = money(10000);

dump($money->formatted());

currencies()->setCurrent('EUR');

// this should be converted from SEK to EUR at this point. But its not
dump($money->formatted());
```

**Comment by stancl** [comment]
Right. Formatting `Money` instances themselves uses their currency — for example if you were displaying prices in separate currencies on one page, doing `$foo->formatted()` and `$bar->formatted()` should respect their currencies.

But I agree that there should be some straightforward abstraction for rendering them in the current currency.

Right now you'd do it like this:
```php
$money->toCurrent()->formatted();
```

Where are you calling the `formatted()`? Is it in a PHP class or a Blade view? Perhaps we could have a Blade directive for this.

**Comment by dalholm** [comment]
Aha. That works too. I am not using formatted in my "original" code. That was just for testing. 

I have your package in my own helper function like below. And just adding `->toCurrent()` did the trick. 

```php
if (! function_exists('formatted_price')) {
    function formatted_price(int $price, int $vat)
    {
        $money = money($price);

        if ((bool) config()->get('app.include_vat')) {
            $money = $money->addTax((float) $vat); // has to be fixed in the package in order to work as expected. 
        }

        return $money->toCurrent();
    }
}
```

Now when i understand your design, i don't think the "magic-swith" i asked for is better then yours. I would have more control with your design. So if you ask me, you could close this! :)

**Comment by stancl** [comment]
Yeah, it's a bit of a complicated issue because I too would expect `$money` to get converted to the current currency when formatting it. But at the same time, I want to be able to use multiple/specific currencies on one page.

So later on I might add either `@money($money)` for formatting it as the current price. Or have different behavior for:
```php
{{ $money }}
{!! $money !!}
```
though I believe that right now, `{{ $money }}` does `$money->formatted()` and `{!! $money !!}` does `$money->value()` for usage e.g. in JS.
